apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: pvc-correction
      containers:
      - name: mariadb
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: database
        securityContext:
          allowPrivilegeEscalation: true
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-pass
                key: password
        image: harbor.kakor.ovh/public/mariadb:latest
