apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-correction
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /Volume1/public/nfs-share-openshift/project-gp-10
    server: 192.168.1.56