apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 250m
      memory: 500Mi
    defaultRequest: # this section defines default requests
      cpu: 250m
      memory: 500Mi
    type: Container